let rol = "customer";

export default [
  {
    description: "should fail when role is invalid",
    data: {
      name: "Test",
      lastName: "User",
      email: "testuser3@gmail.com",
      password: "@Password1234",
      phone: "696981567",
      birthDate: "10/07/1998",
    },
    expectedStatusCode: 400,
    expectedProperty: "rol",
    expectedErrorMessage: "Invalid role",
  },
  {
    description: "should fail when the email is already in use",
    data: {
      name: "Test",
      lastName: "User",
      email: "testuser3@gmail.com",
      password: "@Password1234",
      phone: "696981567",
      birthDate: "10/07/1998",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "email",
    expectedErrorMessage: "Email already in use",
  },
  {
    description: "should fail when the email is missing",
    data: {
      name: "Test",
      lastName: "User",
      password: "@Password1234",
      phone: "696981567",
      birthDate: "10/07/1998",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "emailError",
    expectedErrorMessage: "El correo electrónico es requerido",
  },
  {
    description: "should fail when the email is invalid",
    data: {
      name: "Test",
      lastName: "User",
      email: "testuser3@dedede.com",
      password: "@Password1234",
      phone: "696981567",
      birthDate: "10/07/1998",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "emailError",
    expectedErrorMessage: "El correo electrónico es inválido",
  },
  {
    description: "should fail when the name is missing",
    data: {
      lastName: "Doe",
      email: "johndoe@gmail.com",
      password: "Password1!",
      phone: "+34600123456",
      birthDate: "01/01/2000",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "nameError",
    expectedErrorMessage: "El nombre es requerido",
  },
  {
    description: "should fail when the name is too short",
    data: {
      name: "J",
      lastName: "Doe",
      email: "johndoe@gmail.com",
      password: "Password1!",
      phone: "+34600123456",
      birthDate: "01/01/2000",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "nameError",
    expectedErrorMessage: "El nombre debe tener al menos 3 caracteres",
  },
  {
    description: "should fail when the lastName is missing",
    data: {
      name: "John",
      email: "johndoe@gmail.com",
      password: "Password1!",
      phone: "+34600123456",
      birthDate: "01/01/2000",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "lastNameError",
    expectedErrorMessage: "El apellido es requerido",
  },
  {
    description: "should fail when the lastName is too short",
    data: {
      name: "John",
      lastName: "D",
      email: "johndoe@gmail.com",
      password: "Password1!",
      phone: "+34600123456",
      birthDate: "01/01/2000",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "lastNameError",
    expectedErrorMessage: "El apellido debe tener al menos 3 caracteres",
  },
  {
    description: "should fail when the password is missing",
    data: {
      name: "John",
      lastName: "Doe",
      email: "johndoe@gmail.com",
      phone: "+34600123456",
      birthDate: "01/01/2000",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "passwordError",
    expectedErrorMessage: "La contraseña es requerida",
  },
  {
    description: "should fail when the password is too short",
    data: {
      name: "John",
      lastName: "Doe",
      email: "johndoe@gmail.com",
      password: "Pas1!",
      phone: "600123456",
      birthDate: "01/01/2000",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "passwordError",
    expectedErrorMessage: "La contraseña debe tener al menos 6 caracteres",
  },
  {
    description:
      "should fail when the password does not meet complexity requirements",
    data: {
      name: "John",
      lastName: "Doe",
      email: "johndoe@gmail.com",
      password: "password",
      phone: "+34600123456",
      birthDate: "01/01/2000",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "passwordError",
    expectedErrorMessage:
      "La contraseña debe tener al menos una mayúscula, una minúscula, un número y un caracter especial",
  },
  {
    description: "should fail when the phone is missing",
    data: {
      name: "John",
      lastName: "Doe",
      email: "johndoe@gmail.com",
      password: "Password1!",
      birthDate: "01/01/2000",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "phoneError",
    expectedErrorMessage: "El teléfono es requerido",
  },
  {
    description: "should fail when the phone is invalid",
    data: {
      name: "John",
      lastName: "Doe",
      email: "johndoe@gmail.com",
      password: "Password1!",
      phone: "123456",
      birthDate: "01/01/2000",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "phoneError",
    expectedErrorMessage: "El teléfono es inválido",
  },
  {
    description: "should fail when the birthDate is missing",
    data: {
      name: "John",
      lastName: "Doe",
      email: "johndoe@gmail.com",
      password: "Password1!",
      phone: "600123456",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "birthDateError",
    expectedErrorMessage: "La fecha de nacimiento es requerida",
  },
  {
    description: "should fail when the birthDate is in the future",
    data: {
      name: "John",
      lastName: "Doe",
      email: "johndoe@gmail.com",
      password: "Password1!",
      phone: "600123456",
      birthDate: "01/01/3000",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "birthDateError",
    expectedErrorMessage: "La fecha de nacimiento es inválida",
  },
  {
    description: "should fail when the birthDate format is invalid",
    data: {
      name: "John",
      lastName: "Doe",
      email: "johndoe@gmail.com",
      password: "Password1!",
      phone: "600123456",
      birthDate: "3000-01-01",
      rol: rol,
    },
    expectedStatusCode: 400,
    expectedProperty: "birthDateError",
    expectedErrorMessage: "La fecha de nacimiento es inválida",
  },
];
